
--- 
training_priorities: 
  columns: 
  - priority
  - crew_id
  - name
  - qualification
  - available
  records: 
  - - 1
    - 1
    - name:
    - qualification:
    - available: 1
  - - 2
    - 1
    - name:
    - qualification:
    - available: 1
  - - 3
    - 1
    - name:
    - qualification:
    - available: 1
  - - 4
    - 1
    - name:
    - qualification:
    - available: 1
  - - 5
    - 1
    - name:
    - qualification:
    - available: 1
  - - 6
    - 1
    - name:
    - qualification:
    - available: 1
  - - 7
    - 1
    - name:
    - qualification:
    - available: 1
  - - 8
    - 1
    - name:
    - qualification:
    - available: 1
  - - 9
    - 1
    - name:
    - qualification:
    - available: 1
  - - 10
    - 1
    - name:
    - qualification:
    - available: 1
  - - 1
    - 2
    - name:
    - qualification:
    - available: 1
  - - 2
    - 2
    - name:
    - qualification:
    - available: 1
  - - 3
    - 2
    - name:
    - qualification:
    - available: 1
  - - 4
    - 2
    - name:
    - qualification:
    - available: 1
  - - 5
    - 2
    - name:
    - qualification:
    - available: 1
  - - 6
    - 2
    - name:
    - qualification:
    - available: 1
  - - 7
    - 2
    - name:
    - qualification:
    - available: 1
  - - 8
    - 2
    - name:
    - qualification:
    - available: 1
  - - 9
    - 2
    - name:
    - qualification:
    - available: 1
  - - 10
    - 2
    - name:
    - qualification:
    - available: 1
  - - 1
    - 3
    - name:
    - qualification:
    - available: 1
  - - 2
    - 3
    - name:
    - qualification:
    - available: 1
  - - 3
    - 3
    - name:
    - qualification:
    - available: 1
  - - 4
    - 3
    - name:
    - qualification:
    - available: 1
  - - 5
    - 3
    - name:
    - qualification:
    - available: 1
  - - 6
    - 3
    - name:
    - qualification:
    - available: 1
  - - 7
    - 3
    - name:
    - qualification:
    - available: 1
  - - 8
    - 3
    - name:
    - qualification:
    - available: 1
  - - 9
    - 3
    - name:
    - qualification:
    - available: 1
  - - 10
    - 3
    - name:
    - qualification:
    - available: 1
  - - 1
    - 4
    - name:
    - qualification:
    - available: 1
  - - 2
    - 4
    - name:
    - qualification:
    - available: 1
  - - 3
    - 4
    - name:
    - qualification:
    - available: 1
  - - 4
    - 4
    - name:
    - qualification:
    - available: 1
  - - 5
    - 4
    - name:
    - qualification:
    - available: 1
  - - 6
    - 4
    - name:
    - qualification:
    - available: 1
  - - 7
    - 4
    - name:
    - qualification:
    - available: 1
  - - 8
    - 4
    - name:
    - qualification:
    - available: 1
  - - 9
    - 4
    - name:
    - qualification:
    - available: 1
  - - 10
    - 4
    - name:
    - qualification:
    - available: 1
  - - 1
    - 5
    - name:
    - qualification:
    - available: 1
  - - 2
    - 5
    - name:
    - qualification:
    - available: 1
  - - 3
    - 5
    - name:
    - qualification:
    - available: 1
  - - 4
    - 5
    - name:
    - qualification:
    - available: 1
  - - 5
    - 5
    - name:
    - qualification:
    - available: 1
  - - 6
    - 5
    - name:
    - qualification:
    - available: 1
  - - 7
    - 5
    - name:
    - qualification:
    - available: 1
  - - 8
    - 5
    - name:
    - qualification:
    - available: 1
  - - 9
    - 5
    - name:
    - qualification:
    - available: 1
  - - 10
    - 5
    - name:
    - qualification:
    - available: 1
  - - 1
    - 6
    - name:
    - qualification:
    - available: 1
  - - 2
    - 6
    - name:
    - qualification:
    - available: 1
  - - 3
    - 6
    - name:
    - qualification:
    - available: 1
  - - 4
    - 6
    - name:
    - qualification:
    - available: 1
  - - 5
    - 6
    - name:
    - qualification:
    - available: 1
  - - 6
    - 6
    - name:
    - qualification:
    - available: 1
  - - 7
    - 6
    - name:
    - qualification:
    - available: 1
  - - 8
    - 6
    - name:
    - qualification:
    - available: 1
  - - 9
    - 6
    - name:
    - qualification:
    - available: 1
  - - 10
    - 6
    - name:
    - qualification:
    - available: 1
  - - 1
    - 7
    - name:
    - qualification:
    - available: 1
  - - 2
    - 7
    - name:
    - qualification:
    - available: 1
  - - 3
    - 7
    - name:
    - qualification:
    - available: 1
  - - 4
    - 7
    - name:
    - qualification:
    - available: 1
  - - 5
    - 7
    - name:
    - qualification:
    - available: 1
  - - 6
    - 7
    - name:
    - qualification:
    - available: 1
  - - 7
    - 7
    - name:
    - qualification:
    - available: 1
  - - 8
    - 7
    - name:
    - qualification:
    - available: 1
  - - 9
    - 7
    - name:
    - qualification:
    - available: 1
  - - 10
    - 7
    - name:
    - qualification:
    - available: 1
  - - 1
    - 8
    - name:
    - qualification:
    - available: 1
  - - 2
    - 8
    - name:
    - qualification:
    - available: 1
  - - 3
    - 8
    - name:
    - qualification:
    - available: 1
  - - 4
    - 8
    - name:
    - qualification:
    - available: 1
  - - 5
    - 8
    - name:
    - qualification:
    - available: 1
  - - 6
    - 8
    - name:
    - qualification:
    - available: 1
  - - 7
    - 8
    - name:
    - qualification:
    - available: 1
  - - 8
    - 8
    - name:
    - qualification:
    - available: 1
  - - 9
    - 8
    - name:
    - qualification:
    - available: 1
  - - 10
    - 8
    - name:
    - qualification:
    - available: 1
  - - 1
    - 9
    - name:
    - qualification:
    - available: 1
  - - 2
    - 9
    - name:
    - qualification:
    - available: 1
  - - 3
    - 9
    - name:
    - qualification:
    - available: 1
  - - 4
    - 9
    - name:
    - qualification:
    - available: 1
  - - 5
    - 9
    - name:
    - qualification:
    - available: 1
  - - 6
    - 9
    - name:
    - qualification:
    - available: 1
  - - 7
    - 9
    - name:
    - qualification:
    - available: 1
  - - 8
    - 9
    - name:
    - qualification:
    - available: 1
  - - 9
    - 9
    - name:
    - qualification:
    - available: 1
  - - 10
    - 9
    - name:
    - qualification:
    - available: 1
  - - 1
    - 10
    - name:
    - qualification:
    - available: 1
  - - 2
    - 10
    - name:
    - qualification:
    - available: 1
  - - 3
    - 10
    - name:
    - qualification:
    - available: 1
  - - 4
    - 10
    - name:
    - qualification:
    - available: 1
  - - 5
    - 10
    - name:
    - qualification:
    - available: 1
  - - 6
    - 10
    - name:
    - qualification:
    - available: 1
  - - 7
    - 10
    - name:
    - qualification:
    - available: 1
  - - 8
    - 10
    - name:
    - qualification:
    - available: 1
  - - 9
    - 10
    - name:
    - qualification:
    - available: 1
  - - 10
    - 10
    - name:
    - qualification:
    - available: 1
  - - 1
    - 11
    - name:
    - qualification:
    - available: 1
  - - 2
    - 11
    - name:
    - qualification:
    - available: 1
  - - 3
    - 11
    - name:
    - qualification:
    - available: 1
  - - 4
    - 11
    - name:
    - qualification:
    - available: 1
  - - 5
    - 11
    - name:
    - qualification:
    - available: 1
  - - 6
    - 11
    - name:
    - qualification:
    - available: 1
  - - 7
    - 11
    - name:
    - qualification:
    - available: 1
  - - 8
    - 11
    - name:
    - qualification:
    - available: 1
  - - 9
    - 11
    - name:
    - qualification:
    - available: 1
  - - 10
    - 11
    - name:
    - qualification:
    - available: 1
  - - 1
    - 12
    - name:
    - qualification:
    - available: 1
  - - 2
    - 12
    - name:
    - qualification:
    - available: 1
  - - 3
    - 12
    - name:
    - qualification:
    - available: 1
  - - 4
    - 12
    - name:
    - qualification:
    - available: 1
  - - 5
    - 12
    - name:
    - qualification:
    - available: 1
  - - 6
    - 12
    - name:
    - qualification:
    - available: 1
  - - 7
    - 12
    - name:
    - qualification:
    - available: 1
  - - 8
    - 12
    - name:
    - qualification:
    - available: 1
  - - 9
    - 12
    - name:
    - qualification:
    - available: 1
  - - 10
    - 12
    - name:
    - qualification:
    - available: 1
